
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Apr 13 2026 19:04:03 IST (Apr 13 2026 13:34:03 UTC)

// Verification Directory fv/uart_top 

module uart_top(clk, rst_n, scan_en, scan_in, scan_out, rx, rx_data,
     rx_valid, tx_data, tx_start, tx, tx_busy);
  input clk, rst_n, scan_en, scan_in, rx, tx_start;
  input [7:0] tx_data;
  output scan_out, rx_valid, tx, tx_busy;
  output [7:0] rx_data;
  wire clk, rst_n, scan_en, scan_in, rx, tx_start;
  wire [7:0] tx_data;
  wire scan_out, rx_valid, tx, tx_busy;
  wire [7:0] rx_data;
  wire [3:0] u_rx_sample_cnt;
  wire [7:0] u_rx_shift_reg;
  wire [2:0] u_rx_bit_idx;
  wire [1:0] u_rx_state;
  wire [2:0] u_tx_bit_idx;
  wire [1:0] u_tx_state;
  wire [5:0] u_tx_baud_cnt;
  wire [3:0] u_tx_sample_cnt;
  wire [7:0] u_tx_shift_reg;
  wire n_0, n_1, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_38, n_39, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_53, n_54, n_55, n_56, n_58, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_77;
  wire n_78, n_79, n_80, n_81, n_82, n_83, n_84, n_85;
  wire n_86, n_87, n_88, n_89, n_90, n_91, n_92, n_93;
  wire n_94, n_95, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_103, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_146, n_147, n_148, n_149, n_150;
  wire n_178, n_179, n_180, n_181, n_182, n_183, n_184, n_185;
  wire n_186, n_187, n_188, n_189, n_190, n_191, n_192, n_193;
  wire n_194, n_195, n_196, n_197, n_198, n_199, n_200, n_201;
  wire n_202, n_203, n_204, n_251, n_252, n_253, u_rx_rx_sync0,
       u_rx_rx_sync1;
  wire u_tx_baud_tick;
  assign tx = scan_out;
  OAI31XL g4663__2398(.A0 (u_rx_sample_cnt[0]), .A1
       (u_rx_sample_cnt[1]), .A2 (n_128), .B0 (n_125), .Y (n_131));
  AO22XL g4660__5107(.A0 (u_rx_sample_cnt[3]), .A1 (n_115), .B0 (n_48),
       .B1 (n_91), .Y (n_130));
  OAI31XL g4662__6260(.A0 (n_76), .A1 (u_rx_sample_cnt[2]), .A2
       (n_128), .B0 (n_119), .Y (n_129));
  INVXL g4658(.A (n_123), .Y (n_127));
  SDFFRHQX1 \u_rx_shift_reg_reg[0] (.RN (rst_n), .CK (clk), .D (n_178),
       .SI (u_rx_sample_cnt[3]), .SE (n_253), .Q (u_rx_shift_reg[0]));
  INVXL g4659(.A (n_120), .Y (n_126));
  NAND2XL g4681__4319(.A (u_rx_sample_cnt[1]), .B (n_114), .Y (n_125));
  OAI2BB1XL g4661__8428(.A0N (u_rx_bit_idx[2]), .A1N (n_110), .B0
       (n_108), .Y (n_124));
  AOI21XL g4664__5526(.A0 (u_rx_bit_idx[1]), .A1 (n_112), .B0 (n_88),
       .Y (n_123));
  SDFFRHQX1 \u_rx_shift_reg_reg[4] (.RN (rst_n), .CK (clk), .D (n_179),
       .SI (u_rx_shift_reg[3]), .SE (n_253), .Q (u_rx_shift_reg[4]));
  SDFFRHQX1 \u_rx_state_reg[0] (.RN (rst_n), .CK (clk), .D (n_180), .SI
       (u_rx_shift_reg[7]), .SE (scan_en), .Q (u_rx_state[0]));
  OAI211XL g4648__6783(.A0 (n_148), .A1 (n_49), .B0 (n_109), .C0
       (n_93), .Y (n_122));
  AOI221XL g4665__3680(.A0 (u_tx_bit_idx[2]), .A1 (n_107), .B0 (n_83),
       .B1 (n_103), .C0 (n_104), .Y (n_120));
  OAI2BB1XL g4680__1617(.A0N (n_77), .A1N (n_117), .B0
       (u_rx_sample_cnt[2]), .Y (n_119));
  MXI2XL g4679__2802(.A (n_117), .B (n_128), .S0 (u_rx_sample_cnt[0]),
       .Y (n_118));
  SDFFRHQX1 \u_rx_shift_reg_reg[2] (.RN (rst_n), .CK (clk), .D (n_181),
       .SI (u_rx_shift_reg[1]), .SE (n_251), .Q (u_rx_shift_reg[2]));
  SDFFRHQX1 \u_rx_shift_reg_reg[6] (.RN (rst_n), .CK (clk), .D (n_182),
       .SI (u_rx_shift_reg[5]), .SE (n_251), .Q (u_rx_shift_reg[6]));
  OAI21XL g4678__1705(.A0 (n_111), .A1 (n_63), .B0 (n_85), .Y (n_116));
  OAI21XL g4696__5122(.A0 (n_65), .A1 (n_33), .B0 (n_117), .Y (n_115));
  OAI2BB1XL g4690__8246(.A0N (u_rx_sample_cnt[0]), .A1N (n_75), .B0
       (n_117), .Y (n_114));
  SDFFRHQX1 \u_rx_shift_reg_reg[1] (.RN (rst_n), .CK (clk), .D (n_183),
       .SI (u_rx_shift_reg[0]), .SE (n_252), .Q (u_rx_shift_reg[1]));
  SDFFRHQX1 \u_rx_shift_reg_reg[5] (.RN (rst_n), .CK (clk), .D (n_184),
       .SI (u_rx_shift_reg[4]), .SE (n_252), .Q (u_rx_shift_reg[5]));
  OAI21XL g4694__6131(.A0 (n_13), .A1 (u_rx_bit_idx[0]), .B0 (n_111),
       .Y (n_112));
  OAI2BB1XL g4693__1881(.A0N (n_55), .A1N (n_32), .B0 (n_111), .Y
       (n_110));
  SDFFRHQX1 \u_rx_shift_reg_reg[7] (.RN (rst_n), .CK (clk), .D (n_185),
       .SI (u_rx_shift_reg[6]), .SE (scan_en), .Q (u_rx_shift_reg[7]));
  SDFFRHQX1 \u_rx_shift_reg_reg[3] (.RN (rst_n), .CK (clk), .D (n_186),
       .SI (u_rx_shift_reg[2]), .SE (scan_en), .Q (u_rx_shift_reg[3]));
  SDFFRHQX1 \u_tx_bit_idx_reg[0] (.RN (rst_n), .CK (clk), .D (n_187),
       .SI (u_tx_baud_tick), .SE (n_252), .Q (u_tx_bit_idx[0]));
  AO22XL g4698__5115(.A0 (n_150), .A1 (n_105), .B0 (u_tx_bit_idx[1]),
       .B1 (n_69), .Y (n_106));
  NOR3BXL g4697__7482(.AN (n_105), .B (u_tx_bit_idx[2]), .C (n_103), .Y
       (n_104));
  NAND2XL g4720__4733(.A (u_rx_bit_idx[2]), .B (n_95), .Y (n_102));
  NAND2XL g4701__9315(.A (n_43), .B (n_84), .Y (n_101));
  NOR2XL g4642__9945(.A (n_81), .B (n_86), .Y (n_100));
  OAI211XL g4724__2883(.A0 (n_50), .A1 (u_rx_rx_sync1), .B0 (n_39), .C0
       (n_128), .Y (n_117));
  NOR2XL g4719__2346(.A (u_rx_bit_idx[2]), .B (n_97), .Y (n_99));
  NOR2XL g4717__1666(.A (n_89), .B (n_97), .Y (n_98));
  NAND2XL g4677__7410(.A (n_78), .B (n_31), .Y (n_94));
  SDFFRHQX1 \u_rx_rx_data_reg[2] (.RN (rst_n), .CK (clk), .D (n_188),
       .SI (rx_data[1]), .SE (scan_en), .Q (rx_data[2]));
  NAND2XL g4723__6417(.A (n_62), .B (n_93), .Y (n_111));
  SDFFRHQX1 \u_rx_rx_data_reg[6] (.RN (rst_n), .CK (clk), .D (n_189),
       .SI (rx_data[5]), .SE (n_253), .Q (rx_data[6]));
  SDFFRHQX1 \u_rx_rx_data_reg[7] (.RN (rst_n), .CK (clk), .D (n_190),
       .SI (rx_data[6]), .SE (scan_en), .Q (rx_data[7]));
  SDFFRHQX1 \u_rx_rx_data_reg[0] (.RN (rst_n), .CK (clk), .D (n_191),
       .SI (u_rx_bit_idx[2]), .SE (n_253), .Q (rx_data[0]));
  SDFFRHQX1 \u_rx_rx_data_reg[1] (.RN (rst_n), .CK (clk), .D (n_192),
       .SI (rx_data[0]), .SE (n_253), .Q (rx_data[1]));
  SDFFRHQX1 \u_rx_rx_data_reg[4] (.RN (rst_n), .CK (clk), .D (n_193),
       .SI (rx_data[3]), .SE (n_253), .Q (rx_data[4]));
  SDFFRHQX1 \u_rx_rx_data_reg[3] (.RN (rst_n), .CK (clk), .D (n_194),
       .SI (rx_data[2]), .SE (n_251), .Q (rx_data[3]));
  SDFFRHQX1 \u_rx_rx_data_reg[5] (.RN (rst_n), .CK (clk), .D (n_195),
       .SI (rx_data[4]), .SE (n_251), .Q (rx_data[5]));
  SDFFRHQX1 \u_tx_state_reg[1] (.RN (rst_n), .CK (clk), .D (n_196), .SI
       (u_tx_state[0]), .SE (n_252), .Q (u_tx_state[1]));
  INVXL g4739(.A (n_128), .Y (n_91));
  NAND2XL g4721__5477(.A (n_89), .B (n_88), .Y (n_90));
  NAND2XL g4722__2398(.A (u_rx_bit_idx[2]), .B (n_88), .Y (n_87));
  AOI21XL g4643__5107(.A0 (u_tx_baud_cnt[5]), .A1 (n_66), .B0 (n_67),
       .Y (n_86));
  NOR2XL g4744__6260(.A (u_rx_bit_idx[1]), .B (n_85), .Y (n_95));
  AOI211XL g4726__4319(.A0 (n_19), .A1 (n_83), .B0 (n_38), .C0 (n_53),
       .Y (n_84));
  NOR2XL g4645__8428(.A (n_81), .B (n_64), .Y (n_82));
  OAI31XL g4692__5526(.A0 (n_29), .A1 (u_tx_sample_cnt[3]), .A2 (n_71),
       .B0 (n_58), .Y (n_80));
  NAND2XL g4745__6783(.A (n_89), .B (n_79), .Y (n_108));
  NAND2XL g4742__3680(.A (u_rx_bit_idx[1]), .B (n_68), .Y (n_97));
  NAND2XL g4746__1617(.A (u_rx_bit_idx[2]), .B (n_79), .Y (n_109));
  NOR2XL g4754__2802(.A (u_tx_state[0]), .B (n_107), .Y (n_105));
  AOI21XL g4699__1705(.A0 (u_tx_state[0]), .A1 (n_56), .B0 (n_149), .Y
       (n_78));
  NAND2XL g4741__5122(.A (n_76), .B (n_75), .Y (n_77));
  OR2XL g4743__8246(.A (u_rx_rx_sync1), .B (n_74), .Y (n_93));
  NAND2XL g4747__7098(.A (u_tx_baud_tick), .B (n_75), .Y (n_128));
  INVXL g4767(.A (n_92), .Y (n_73));
  OAI31XL g4695__6131(.A0 (u_tx_sample_cnt[0]), .A1
       (u_tx_sample_cnt[1]), .A2 (n_71), .B0 (n_45), .Y (n_72));
  OAI32XL g4691__1881(.A0 (n_34), .A1 (u_tx_sample_cnt[2]), .A2 (n_71),
       .B0 (n_35), .B1 (n_0), .Y (n_70));
  OAI21XL g4752__5115(.A0 (u_tx_state[0]), .A1 (u_tx_bit_idx[0]), .B0
       (n_54), .Y (n_69));
  INVXL g4757(.A (n_68), .Y (n_85));
  NOR2XL g4646__7482(.A (u_tx_baud_cnt[5]), .B (n_66), .Y (n_67));
  INVXL g4758(.A (n_75), .Y (n_65));
  OAI21XL g4649__4733(.A0 (n_51), .A1 (u_tx_baud_cnt[4]), .B0 (n_66),
       .Y (n_64));
  NOR3XL g4755__6161(.A (u_rx_bit_idx[1]), .B (n_63), .C (n_62), .Y
       (n_88));
  MXI2XL g4715__9315(.A (n_28), .B (n_71), .S0 (u_tx_sample_cnt[0]), .Y
       (n_61));
  INVXL g4765(.A (n_59), .Y (n_60));
  OAI21XL g4713__9945(.A0 (n_44), .A1 (n_30), .B0 (u_tx_sample_cnt[3]),
       .Y (n_58));
  NOR2XL g4769__2346(.A (n_55), .B (n_62), .Y (n_79));
  NOR2XL g4762__1666(.A (u_rx_bit_idx[0]), .B (n_62), .Y (n_68));
  INVXL g4766(.A (n_54), .Y (n_107));
  NOR3XL g4748__7410(.A (u_tx_state[0]), .B (u_tx_bit_idx[2]), .C
       (n_25), .Y (n_53));
  NAND3BXL g4761__5477(.AN (n_50), .B (n_49), .C (n_48), .Y (n_74));
  OAI21XL g4763__2398(.A0 (n_48), .A1 (n_47), .B0 (n_49), .Y (n_75));
  OR2XL g4773__5107(.A (n_24), .B (n_46), .Y (n_92));
  OAI21XL g4714__6260(.A0 (n_44), .A1 (n_14), .B0 (u_tx_sample_cnt[1]),
       .Y (n_45));
  NOR2BXL g4771__4319(.AN (n_43), .B (n_56), .Y (n_54));
  NOR2XL g4725__8428(.A (n_27), .B (n_81), .Y (n_42));
  NOR2XL g4770__5526(.A (n_17), .B (n_56), .Y (n_59));
  NAND2XL g4667__6783(.A (u_tx_baud_cnt[4]), .B (n_51), .Y (n_66));
  NOR2XL g4751__3680(.A (n_12), .B (n_81), .Y (n_41));
  NOR2BXL g4774__1617(.AN (n_150), .B (n_18), .Y (n_38));
  AOI21XL g4740__2802(.A0 (n_34), .A1 (n_21), .B0 (n_44), .Y (n_35));
  NAND4BXL g4775__1705(.AN (n_50), .B (u_rx_state[1]), .C
       (u_rx_sample_cnt[3]), .D (n_33), .Y (n_46));
  NAND4XL g4776__5122(.A (u_tx_baud_tick), .B (u_rx_sample_cnt[3]), .C
       (n_32), .D (n_33), .Y (n_62));
  SDFFRHQX1 \u_tx_shift_reg_reg[3] (.RN (rst_n), .CK (clk), .D (n_197),
       .SI (u_tx_shift_reg[2]), .SE (scan_en), .Q (u_tx_shift_reg[3]));
  SDFFRHQX1 \u_tx_shift_reg_reg[2] (.RN (rst_n), .CK (clk), .D (n_198),
       .SI (u_tx_shift_reg[1]), .SE (n_251), .Q (u_tx_shift_reg[2]));
  SDFFRHQX1 \u_tx_shift_reg_reg[4] (.RN (rst_n), .CK (clk), .D (n_199),
       .SI (u_tx_shift_reg[3]), .SE (n_253), .Q (u_tx_shift_reg[4]));
  SDFFRHQX1 \u_tx_shift_reg_reg[5] (.RN (rst_n), .CK (clk), .D (n_200),
       .SI (u_tx_shift_reg[4]), .SE (n_252), .Q (u_tx_shift_reg[5]));
  SDFFRHQX1 \u_tx_shift_reg_reg[0] (.RN (rst_n), .CK (clk), .D (n_201),
       .SI (u_tx_sample_cnt[3]), .SE (n_253), .Q (u_tx_shift_reg[0]));
  SDFFRHQX1 \u_tx_shift_reg_reg[1] (.RN (rst_n), .CK (clk), .D (n_202),
       .SI (u_tx_shift_reg[0]), .SE (n_252), .Q (u_tx_shift_reg[1]));
  SDFFRHQX1 \u_tx_shift_reg_reg[7] (.RN (rst_n), .CK (clk), .D (n_203),
       .SI (u_tx_shift_reg[6]), .SE (scan_en), .Q (u_tx_shift_reg[7]));
  SDFFRHQX1 \u_tx_shift_reg_reg[6] (.RN (rst_n), .CK (clk), .D (n_204),
       .SI (u_tx_shift_reg[5]), .SE (n_251), .Q (u_tx_shift_reg[6]));
  NOR2BXL g4781__8246(.AN (n_29), .B (n_20), .Y (n_30));
  INVXL g4759(.A (n_44), .Y (n_28));
  NOR2BXL g4787__7098(.AN (n_33), .B (u_rx_sample_cnt[3]), .Y (n_48));
  NAND3BXL g4777__6131(.AN (n_29), .B (u_tx_baud_tick), .C
       (u_tx_sample_cnt[3]), .Y (n_56));
  OAI21XL g4768__1881(.A0 (n_15), .A1 (u_tx_baud_cnt[2]), .B0 (n_26),
       .Y (n_27));
  AOI21XL g4779__5115(.A0 (u_tx_shift_reg[3]), .A1 (n_10), .B0 (n_16),
       .Y (n_25));
  NAND3XL g4791__7482(.A (n_24), .B (n_47), .C (n_49), .Y (n_39));
  NOR2XL g4736__4733(.A (n_23), .B (n_26), .Y (n_51));
  OAI2BB1XL g4760__6161(.A0N (tx_busy), .A1N (n_21), .B0 (n_31), .Y
       (n_22));
  OAI22XL g4764__9315(.A0 (tx_start), .A1 (n_21), .B0 (n_20), .B1
       (u_tx_baud_tick), .Y (n_44));
  OAI22XL g4780__9945(.A0 (n_8), .A1 (u_tx_bit_idx[0]), .B0 (n_103),
       .B1 (n_1), .Y (n_19));
  AOI32XL g4789__2883(.A0 (n_5), .A1 (u_tx_shift_reg[1]), .A2 (n_17),
       .B0 (n_83), .B1 (u_tx_shift_reg[5]), .Y (n_18));
  AND3XL g4772__2346(.A (u_tx_baud_cnt[0]), .B (u_tx_baud_cnt[4]), .C
       (n_11), .Y (n_81));
  NAND2BXL g4793__1666(.AN (n_34), .B (u_tx_sample_cnt[2]), .Y (n_29));
  NAND2XL g4784__7410(.A (u_tx_baud_tick), .B (n_21), .Y (n_71));
  NOR2BXL g4794__6417(.AN (u_rx_sample_cnt[2]), .B (n_76), .Y (n_33));
  NOR2XL g4786__5477(.A (u_tx_bit_idx[0]), .B (n_7), .Y (n_16));
  NAND2XL g4783__2398(.A (u_tx_baud_cnt[2]), .B (n_15), .Y (n_26));
  NOR2XL g4782__5107(.A (n_9), .B (n_20), .Y (n_14));
  AOI21XL g4798__6260(.A0 (u_tx_state[1]), .A1 (u_tx_state[0]), .B0
       (n_20), .Y (n_43));
  NAND2X1 g4778__4319(.A (n_20), .B (tx_start), .Y (n_31));
  INVXL g4807(.A (n_32), .Y (n_13));
  OAI21XL g4796__8428(.A0 (u_tx_baud_cnt[1]), .A1 (u_tx_baud_cnt[0]),
       .B0 (n_6), .Y (n_12));
  NOR4BBXL g4790__5526(.AN (u_tx_baud_cnt[5]), .BN (u_tx_baud_cnt[2]),
       .C (u_tx_baud_cnt[1]), .D (u_tx_baud_cnt[3]), .Y (n_11));
  INVXL g4801(.A (n_103), .Y (n_10));
  NAND2XL g4804__6783(.A (n_4), .B (u_rx_sample_cnt[1]), .Y (n_76));
  NAND2XL g4803__3680(.A (n_9), .B (u_tx_sample_cnt[1]), .Y (n_34));
  INVXL g4785(.A (n_20), .Y (n_21));
  MXI2XL g4792__1617(.A (u_tx_shift_reg[4]), .B (u_tx_shift_reg[6]),
       .S0 (u_tx_bit_idx[1]), .Y (n_8));
  MXI2XL g4797__2802(.A (u_tx_shift_reg[0]), .B (u_tx_shift_reg[2]),
       .S0 (u_tx_bit_idx[1]), .Y (n_7));
  INVXL g4800(.A (n_6), .Y (n_15));
  NOR2XL g4811__5122(.A (u_rx_state[0]), .B (n_49), .Y (n_32));
  NOR2XL g4812__8246(.A (u_tx_state[0]), .B (n_5), .Y (n_83));
  NAND2XL g4810__7098(.A (u_rx_state[0]), .B (u_tx_baud_tick), .Y
       (n_50));
  NAND2XL g4806__6131(.A (u_tx_bit_idx[0]), .B (u_tx_bit_idx[1]), .Y
       (n_103));
  NOR2XL g4813__1881(.A (u_tx_state[0]), .B (u_tx_state[1]), .Y (n_20));
  NAND2XL g4805__5115(.A (u_tx_baud_cnt[0]), .B (u_tx_baud_cnt[1]), .Y
       (n_6));
  NAND2XL g4809__7482(.A (u_rx_bit_idx[0]), .B (u_rx_bit_idx[1]), .Y
       (n_55));
  INVXL g4819(.A (u_tx_state[0]), .Y (n_17));
  INVXL g4826(.A (u_rx_bit_idx[2]), .Y (n_89));
  INVXL g4820(.A (u_tx_shift_reg[7]), .Y (n_1));
  INVXL g4821(.A (u_tx_sample_cnt[2]), .Y (n_0));
  INVXL g4822(.A (u_tx_bit_idx[2]), .Y (n_5));
  INVXL g4817(.A (u_rx_bit_idx[0]), .Y (n_63));
  INVXL g4814(.A (u_tx_baud_cnt[3]), .Y (n_23));
  INVXL g4824(.A (u_rx_state[0]), .Y (n_47));
  INVXL g4818(.A (u_rx_state[1]), .Y (n_49));
  INVXL g4881(.A (u_tx_baud_cnt[0]), .Y (n_36));
  AOI21XL g2(.A0 (n_26), .A1 (n_23), .B0 (n_51), .Y (n_146));
  NOR2BXL g4882(.AN (n_95), .B (u_rx_bit_idx[2]), .Y (n_147));
  NAND4XL g4883(.A (n_39), .B (n_46), .C (n_74), .D (n_109), .Y
       (n_148));
  NOR4BBXL g4884(.AN (n_83), .BN (u_tx_state[1]), .C (n_103), .D
       (n_56), .Y (n_149));
  NOR2BXL g4885(.AN (u_tx_bit_idx[0]), .B (u_tx_bit_idx[1]), .Y
       (n_150));
  SDFFRHQX1 \u_rx_sample_cnt_reg[1] (.RN (rst_n), .CK (clk), .D
       (n_131), .SI (u_rx_sample_cnt[0]), .SE (n_252), .Q
       (u_rx_sample_cnt[1]));
  SDFFRHQX1 \u_rx_sample_cnt_reg[2] (.RN (rst_n), .CK (clk), .D
       (n_129), .SI (u_rx_sample_cnt[1]), .SE (n_251), .Q
       (u_rx_sample_cnt[2]));
  SDFFRHQX1 \u_rx_sample_cnt_reg[3] (.RN (rst_n), .CK (clk), .D
       (n_130), .SI (u_rx_sample_cnt[2]), .SE (n_251), .Q
       (u_rx_sample_cnt[3]));
  SDFFRHQX4 \u_rx_bit_idx_reg[1] (.RN (rst_n), .CK (clk), .D (n_127),
       .SI (u_rx_bit_idx[0]), .SE (n_251), .Q (u_rx_bit_idx[1]));
  SDFFRHQX1 \u_tx_bit_idx_reg[2] (.RN (rst_n), .CK (clk), .D (n_126),
       .SI (u_tx_bit_idx[1]), .SE (n_253), .Q (u_tx_bit_idx[2]));
  SDFFRHQX4 \u_rx_bit_idx_reg[2] (.RN (rst_n), .CK (clk), .D (n_124),
       .SI (u_rx_bit_idx[1]), .SE (n_252), .Q (u_rx_bit_idx[2]));
  SDFFRHQX1 \u_rx_state_reg[1] (.RN (rst_n), .CK (clk), .D (n_122), .SI
       (u_rx_state[0]), .SE (n_252), .Q (u_rx_state[1]));
  SDFFRXL \u_rx_sample_cnt_reg[0] (.RN (rst_n), .CK (clk), .D (n_118),
       .SI (rx_valid), .SE (scan_en), .Q (n_4), .QN
       (u_rx_sample_cnt[0]));
  SDFFRHQX1 \u_rx_bit_idx_reg[0] (.RN (rst_n), .CK (clk), .D (n_116),
       .SI (scan_in), .SE (n_252), .Q (u_rx_bit_idx[0]));
  SDFFSHQX2 u_tx_tx_reg(.SN (rst_n), .CK (clk), .D (n_101), .SI
       (tx_busy), .SE (scan_en), .Q (scan_out));
  SDFFRHQX1 \u_tx_baud_cnt_reg[5] (.RN (rst_n), .CK (clk), .D (n_100),
       .SI (u_tx_baud_cnt[4]), .SE (scan_en), .Q (u_tx_baud_cnt[5]));
  SDFFRHQX4 \u_tx_bit_idx_reg[1] (.RN (rst_n), .CK (clk), .D (n_106),
       .SI (u_tx_bit_idx[0]), .SE (n_253), .Q (u_tx_bit_idx[1]));
  SDFFRHQX4 \u_tx_state_reg[0] (.RN (rst_n), .CK (clk), .D (n_94), .SI
       (u_tx_shift_reg[7]), .SE (n_251), .Q (u_tx_state[0]));
  SDFFRHQX1 \u_tx_baud_cnt_reg[4] (.RN (rst_n), .CK (clk), .D (n_82),
       .SI (u_tx_baud_cnt[3]), .SE (n_251), .Q (u_tx_baud_cnt[4]));
  SDFFRHQX1 \u_tx_sample_cnt_reg[3] (.RN (rst_n), .CK (clk), .D (n_80),
       .SI (u_tx_sample_cnt[2]), .SE (scan_en), .Q
       (u_tx_sample_cnt[3]));
  SDFFRHQX8 u_rx_rx_valid_reg(.RN (rst_n), .CK (clk), .D (n_73), .SI
       (n_24), .SE (n_253), .Q (rx_valid));
  SDFFRHQX1 \u_tx_sample_cnt_reg[1] (.RN (rst_n), .CK (clk), .D (n_72),
       .SI (u_tx_sample_cnt[0]), .SE (n_252), .Q (u_tx_sample_cnt[1]));
  SDFFRHQX1 \u_tx_sample_cnt_reg[2] (.RN (rst_n), .CK (clk), .D (n_70),
       .SI (u_tx_sample_cnt[1]), .SE (n_251), .Q (u_tx_sample_cnt[2]));
  SDFFRHQX1 \u_tx_baud_cnt_reg[3] (.RN (rst_n), .CK (clk), .D (n_146),
       .SI (u_tx_baud_cnt[2]), .SE (n_252), .Q (u_tx_baud_cnt[3]));
  SDFFRXL \u_tx_sample_cnt_reg[0] (.RN (rst_n), .CK (clk), .D (n_61),
       .SI (u_tx_bit_idx[2]), .SE (n_253), .Q (n_9), .QN
       (u_tx_sample_cnt[0]));
  SDFFRHQX1 \u_tx_baud_cnt_reg[2] (.RN (rst_n), .CK (clk), .D (n_42),
       .SI (u_tx_baud_cnt[1]), .SE (n_253), .Q (u_tx_baud_cnt[2]));
  SDFFRHQX1 \u_tx_baud_cnt_reg[1] (.RN (rst_n), .CK (clk), .D (n_41),
       .SI (u_tx_baud_cnt[0]), .SE (scan_en), .Q (u_tx_baud_cnt[1]));
  SDFFRHQX1 \u_tx_baud_cnt_reg[0] (.RN (rst_n), .CK (clk), .D (n_36),
       .SI (u_rx_state[1]), .SE (scan_en), .Q (u_tx_baud_cnt[0]));
  SDFFRHQX8 u_tx_tx_busy_reg(.RN (rst_n), .CK (clk), .D (n_22), .SI
       (u_tx_state[1]), .SE (n_251), .Q (tx_busy));
  SDFFRHQX4 u_tx_baud_tick_reg(.RN (rst_n), .CK (clk), .D (n_81), .SI
       (u_tx_baud_cnt[5]), .SE (n_252), .Q (u_tx_baud_tick));
  SDFFSHQX1 u_rx_rx_sync0_reg(.SN (rst_n), .CK (clk), .D (rx), .SI
       (rx_data[7]), .SE (scan_en), .Q (u_rx_rx_sync0));
  SDFFSXL u_rx_rx_sync1_reg(.SN (rst_n), .CK (clk), .D (u_rx_rx_sync0),
       .SI (u_rx_rx_sync0), .SE (n_253), .Q (u_rx_rx_sync1), .QN
       (n_24));
  MX2XL g19(.A (u_rx_shift_reg[0]), .B (u_rx_rx_sync1), .S0 (n_147), .Y
       (n_178));
  MX2XL g4915(.A (u_rx_rx_sync1), .B (u_rx_shift_reg[4]), .S0 (n_102),
       .Y (n_179));
  MX2XL g4916(.A (u_rx_state[0]), .B (n_47), .S0 (n_148), .Y (n_180));
  MX2XL g4917(.A (u_rx_shift_reg[2]), .B (u_rx_rx_sync1), .S0 (n_99),
       .Y (n_181));
  MX2XL g4918(.A (u_rx_shift_reg[6]), .B (u_rx_rx_sync1), .S0 (n_98),
       .Y (n_182));
  MX2XL g4919(.A (u_rx_rx_sync1), .B (u_rx_shift_reg[1]), .S0 (n_90),
       .Y (n_183));
  MX2XL g4920(.A (u_rx_rx_sync1), .B (u_rx_shift_reg[5]), .S0 (n_87),
       .Y (n_184));
  MX2XL g4921(.A (u_rx_rx_sync1), .B (u_rx_shift_reg[7]), .S0 (n_109),
       .Y (n_185));
  MX2XL g4922(.A (u_rx_rx_sync1), .B (u_rx_shift_reg[3]), .S0 (n_108),
       .Y (n_186));
  MX2XL g4923(.A (n_105), .B (n_107), .S0 (u_tx_bit_idx[0]), .Y
       (n_187));
  MX2XL g4924(.A (u_rx_shift_reg[2]), .B (rx_data[2]), .S0 (n_92), .Y
       (n_188));
  MX2XL g4925(.A (u_rx_shift_reg[6]), .B (rx_data[6]), .S0 (n_92), .Y
       (n_189));
  MX2XL g4926(.A (u_rx_shift_reg[7]), .B (rx_data[7]), .S0 (n_92), .Y
       (n_190));
  MX2XL g4927(.A (u_rx_shift_reg[0]), .B (rx_data[0]), .S0 (n_92), .Y
       (n_191));
  MX2XL g4928(.A (u_rx_shift_reg[1]), .B (rx_data[1]), .S0 (n_92), .Y
       (n_192));
  MX2XL g4929(.A (u_rx_shift_reg[4]), .B (rx_data[4]), .S0 (n_92), .Y
       (n_193));
  MX2XL g4930(.A (u_rx_shift_reg[3]), .B (rx_data[3]), .S0 (n_92), .Y
       (n_194));
  MX2XL g4931(.A (u_rx_shift_reg[5]), .B (rx_data[5]), .S0 (n_92), .Y
       (n_195));
  MX2XL g4932(.A (n_59), .B (n_60), .S0 (u_tx_state[1]), .Y (n_196));
  MX2XL g4933(.A (tx_data[3]), .B (u_tx_shift_reg[3]), .S0 (n_31), .Y
       (n_197));
  MX2XL g4934(.A (tx_data[2]), .B (u_tx_shift_reg[2]), .S0 (n_31), .Y
       (n_198));
  MX2XL g4935(.A (tx_data[4]), .B (u_tx_shift_reg[4]), .S0 (n_31), .Y
       (n_199));
  MX2XL g4936(.A (tx_data[5]), .B (u_tx_shift_reg[5]), .S0 (n_31), .Y
       (n_200));
  MX2XL g4937(.A (tx_data[0]), .B (u_tx_shift_reg[0]), .S0 (n_31), .Y
       (n_201));
  MX2XL g4938(.A (tx_data[1]), .B (u_tx_shift_reg[1]), .S0 (n_31), .Y
       (n_202));
  MX2XL g4939(.A (tx_data[7]), .B (u_tx_shift_reg[7]), .S0 (n_31), .Y
       (n_203));
  MX2XL g4940(.A (tx_data[6]), .B (u_tx_shift_reg[6]), .S0 (n_31), .Y
       (n_204));
  BUFX2 drc_buf_sp4986(.A (scan_en), .Y (n_251));
  BUFX2 drc_buf_sp4987(.A (scan_en), .Y (n_252));
  BUFX2 drc_buf_sp4988(.A (scan_en), .Y (n_253));
endmodule

